delete keys api
go-bazzinga/yral-metadata pull request #2
Opened 2024-04-25 16:02 UTC by komal-rs

2024-04-25 16:08 UTC, rupansh-gob commented
Either use hashing or use something standard like JWT for authentication

2024-04-25 19:15 UTC, rupansh-gob requested changes

2024-04-25 19:15 UTC, rupansh-gob commented on server/src/api.rs
> +    match conn.del::<Vec<String>, bool>(keys).await {
Use `hdel`!
This would've been a destructive change and possibly broken authentication

2024-04-27 14:58 UTC, komal-rs commented on server/src/api.rs
> +    match conn.del::<Vec<String>, bool>(keys).await {
Changed to hdel. The key is still getting deleted if there is only 1 field. Is this expected ?

2024-04-28 07:24 UTC, rupansh-gob requested changes

2024-04-28 07:24 UTC, rupansh-gob commented on server/src/api.rs
> +    let futures_iter = keys.iter().map(|key| async {
use https://docs.rs/futures/latest/futures/stream/struct.FuturesUnordered.html

2024-04-28 07:24 UTC, rupansh-gob commented on server/src/api.rs
> +        match res {
map_err

2024-04-28 07:24 UTC, rupansh-gob commented on server/src/api.rs
> +    if !errors.is_empty() {
Return the errors in ApiResult instead of logging.

2024-04-28 07:24 UTC, rupansh-gob commented on server/src/api.rs
> +        .ok_or(Error::AuthToken("missing Authorization header".to_string()))?
Make proper Error variants instead of one catch all variant, We would be using anyhow instead of thiserror if we wanted that.

2024-04-28 07:24 UTC, rupansh-gob commented on server/src/api.rs
> +    match verify_token(token) {
Ideally i'd use a middleware to verify the bearer token but this is fine as we currently only use it for one endpoint

2024-04-28 07:25 UTC, rupansh-gob commented
Also update https://github.com/go-bazzinga/yral-metadata/blob/master/client/src/lib.rs

2024-04-29 04:04 UTC, rupansh-gob commented on server/src/auth.rs
> +    validation.validate_exp = false;
> since the key won't change, we don't need exp (expiration time)
the expiration time is for the token i believe

2024-04-29 04:09 UTC, komal-rs commented on server/src/auth.rs
> +    validation.validate_exp = false;
*token , sorry

2024-04-29 04:10 UTC, rupansh-gob commented on server/src/auth.rs
> +    validation.validate_exp = false;
> *token , sorry

not safe to assume we wont rotate keys and/or tokens

2024-04-29 04:12 UTC, komal-rs commented on server/src/auth.rs
> +    validation.validate_exp = false;
yeah, but changing something hardcoded will be a very hectic process. Don't think that is standard anywhere. We might have to hcange the whole architecture, when that can be added anyway

2024-04-29 04:14 UTC, rupansh-gob commented on server/src/auth.rs
> +    validation.validate_exp = false;
> yeah, but changing something hardcoded will be a very hectic process. Don't think that is standard anywhere. We might have to hcange the whole architecture, when that can be added anyway

token rotation and key rotation is very common, We can enable the flag later if you have very strong opinions about this.

2024-04-29 04:16 UTC, komal-rs commented on server/src/auth.rs
> +    validation.validate_exp = false;
Don't think hardcoding and rotating it is common is what I was saying.

2024-04-29 04:17 UTC, komal-rs commented on server/src/auth.rs
> +    validation.validate_exp = false;
Here we are the one creating the private key, generating token manually and adding in GH secret.

2024-04-29 04:28 UTC, rupansh-gob commented on server/src/auth.rs
> +    validation.validate_exp = false;
> Here we are the one creating the private key, generating token manually and adding in GH secret.

I dont see how it wont have a token expiry, and where we're assuming that we wont generate the token manually again. Anyways if you think its not worth the effort, feel free to skip on this

2024-04-30 06:12 UTC, rupansh-gob requested changes

2024-04-30 06:12 UTC, rupansh-gob commented on server/src/api.rs
> +        .join("; ");
you can skip on map and join

2024-04-30 06:12 UTC, rupansh-gob commented on server/src/api.rs
> +                .map_err(|e| (key.to_string(), e.to_string()))
You can skip to_string()

2024-04-30 06:12 UTC, rupansh-gob commented on server/src/auth.rs
> +    let public_key = env::var("JWT_PUBLIC_KEY").expect("JWT_PUBLIC_KEY not set");
We have `server/src/config.rs` for env variables, please use it.
add a field `jwt_public_key: String`

2024-04-30 06:12 UTC, rupansh-gob commented on server/src/auth.rs
> +    if token_message.claims != *CLAIMS {
Since you don't need to compare the expiry, just compare sub & company.

2024-04-30 06:12 UTC, rupansh-gob commented on server/src/consts.rs
> +});
remove unnecessary variable

2024-04-30 06:12 UTC, rupansh-gob commented on types/src/error.rs
> +    #[error("error deleting few keys: {0}")]
#[error("failed to delete all keys (redis)")]
DeleteKeys,

2024-04-30 06:12 UTC, rupansh-gob commented on client/src/lib.rs
> +    pub async fn delete_metadata_bulk(&self, users: Vec<Principal>) -> Result<()> {
I'd prefer you use const generics for authenticated endpoints, similar to how we do it for canisters
See: https://github.com/go-bazzinga/hot-or-not-web-leptos-ssr/blob/main/src/state/canisters.rs

2024-04-30 06:19 UTC, komal-rs commented on server/src/consts.rs
> +});
have to include exp or else will have to do what I was doing previously of setting validate_exp as false. Let's just keep it for future.

2024-04-30 08:57 UTC, rupansh approved these changes

2024-04-30 08:58 UTC, rupansh-gob approved these changes

2024-04-30 08:59 UTC, merged